apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-manager
  namespace: network-system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: magicsong/ks-network:90fa3885
        name: manager
