services:
  - docker

language: go

git:
  depth: false

go:
  - 1.12

go_import_path: kubesphere.io/kubesphere

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

before_script:
  - dep ensure -v
  - docker --version

script:
  - make test
  - bash hack/docker_build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: bash hack/docker_push.sh
  on:
    branch: master