apiVersion: iam.kubesphere.io/v1alpha2
kind: User
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: admin
spec:
  email: admin@kubesphere.io
  password: $2a$04$wr/XmTQ99uQpgi335xPyoOM08h34ZQk265pdqHMv5Yw6Xo2vfiO/6
